<?php

/**
 * @file - Addes new customers
 */


/**
 * Implements hook_menu().
 */
function sergiodebuger_menu() {
    // Note: we can't dynamically append destination to querystring.
    // Do so at theme layer. Fix in D7?
    $items['addcustomer/%'] = array(
        'title' => 'Add Customers',
        'page callback' => 'sergiodebuger_add_customers',
        'page arguments' => array(1),
        // 'description' => '',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
        'file' => 'includes/sergiodebuger.customers.inc',
    );
    return $items;
}
