<?php

/**
 * @file - Addes new customers
 */


module_load_include('inc', 'sergiodebuger', 'sergiodebuger.func');


/**
 * Implements hook_menu().
 */
function sergiodebuger_menu() {

    $items['addcustomer/%'] = array(
        'title' => 'Add Customers',
        'page callback' => 'sergiodebuger_add_customers',
        'page arguments' => array(1),
        // 'description' => '',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
        'file' => 'includes/sergiodebuger.customers.inc',
    );
	
	
    return $items;
}
